[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "leco"
version = "0.0.1"
authors = [{ name = "Anke Posma", email = "a.j.posma1@uu.nl" }]
description = "Package containing the Leco model"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["docopt"]

[project.urls]
"Homepage" = "https://github.com/computationalgeography/leco"
"Bug Tracker" = "https://github.com/computationalgeography/leco/issues"

[project.scripts]
leco_model = "leco.cli.leco:main"

[tool.pyright]
exclude = [
    # TODO: fix all issues and remove these lines
    "source/package/**",
    "source/test/**",
]
extraPaths = ["source/package"]

[tool.hatch.build.targets.wheel]
packages = ["source/package/leco"]

[tool.ruff]
line-length = 110
exclude = [
    ### sensitivity_analysis files are under development and might nog be needed
    "source/package/leco/sensitivity_analysis",
    ## Unclear problem
    "documentation/",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # 'print' statement found
    "T201",
    # too many arguments in function definition
    "PLR0913",
    # specifying long messages outside exception class      #WANT TO LEAVE VALUE ERRORS OUT EVENTUALLY ANYWAYS
    "TRY003",
    # allow magic variables to be defined
    "PLR2004",
    # need to specify timezone
    "DTZ005",
    # Specify docstring at start of file
    "D100",
    # Prefer absolute inputs of relative inputs
    "TID252",
    # Boolean (typed / default) positional value in function call
    "FBT001",
    "FBT002",
    "FBT003",
    # Use a regular 'assert' instead of unittest-style 'assertNotIn'
    "PT009",
    # Shebang is present but file is not executable; discuss with Kor
    "EXE001",
    "EM101",
    "EM102",
    "S101",
    "TD002",
    "TD003",
    "FIX002",
]

# Ignore specific commands for the following files
[tool.ruff.lint.per-file-ignores]
"source/package/leco/cli/main.py" = ["D103", "ANN002", "ANN003", "BLE001"]
# "source/package/leco/cli/spawn.py" = ["D103", "S101"]
"source/test/*" = [
    "D101",
    "ANN201",
    "D102",
    "D104",
    "PLR0402",
    "I001",
    "D103",
    "PTH120",
]
"environment/script/*.py" = ["INP001"]
