[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "leco"
version = "0.0.1"
authors = [{ name = "Anke Posma", email = "a.j.posma1@uu.nl" }]
description = "Package containing the Leco model"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["docopt"]

[project.urls]
"Homepage" = "https://github.com/computationalgeography/leco"
"Bug Tracker" = "https://github.com/computationalgeography/leco/issues"

[project.scripts]
leco_model = "leco.cli.leco:main"

[tool.hatch.build.targets.wheel]
packages = ["source/package/leco"]

[tool.ruff]
line-length = 110
fix = true

[tool.lint]
select = ["ALL"]
ignore = [
    # 'print' statement found
    "T201",
    # too many arguments in function definition
    "PLR0913",
    # specifying long messages outside exception class      #WANT TO LEAVE VALUEERROS OUT EVENTUALLY ANYWAYS
    "TRY003",
    # allow magic variables to be defined
    "PLR2004",
    # need to specify timezone
    "DTZ005",
    # Specify docstring at start of file
    "D100",
]
