[initialization]
agents = 5
steps = 20
seed = 51
write_interval = 200
nr_start_languages = 5

[space]
shape = [1000, 1000]

[initialization_subset_area]
present = false
x_extent = [480,520]
y_extent = [930,970]

[barrier]
present = false
x_extent = [250, 450]
y_extent = [0, 1000]
impermeability = 0.6

[movement]
speed = 20

[language]
meanings = 100
forms = 120
mutation_rate = 0.001

[population_dynamics]
death_rate = 0.01
birth_rate = 0.01
logistic_growth = true
carrying_capacity = 10
end_growth_time = 50

[interaction]
radius = 20
partner_proportion = 0.8
diffusion_rate = 0.01
similarity_preference = 0.2
