[initialization]
agents = 1000
steps = 1000
seed = 42
nr_start_languages = 1

[space]
shape = [1000, 1000]

[initialization_subset_area]
present = false
x_extent = [480,520]
y_extent = [930,970]

[barrier]
present = false
x_extent = [250, 450]
y_extent = [0, 1000]
impermeability = 0.6

[movement]
speed = 20

[language]
meanings = 100
forms = 120
mutation_rate = 0.0001

[population_dynamics]
death_rate = 0.0005
birth_rate = 0.0005
logistic_growth = false
carrying_capacity = 10
end_growth_time = 50

[interaction]
radius = 30
partner_proportion = 0.3
diffusion_rate = 0.07
similarity_preference = 0.5
