name: Test

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.platform.os }} / ${{ matrix.platform.arch }} / python-${{ matrix.python_version }}
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 5
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        # min version, max version
        # 3.11 is the first version supported by darwin / arm64 runner
        python_version: ["3.11", "3.14"]
        platform:
          - { os: "macos-15", arch: arm64 }
          - { os: "ubuntu-24.04", arch: x64 }
          - { os: "windows-2025", arch: x64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        id: py
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - name: Install packages
        run: |
          py_interpreter="${{ steps.py.outputs.python-path }}"
          $py_interpreter -m pip install \
            -r environment/configuration/requirements.txt
      - name: Run commands
        run: |
          py_interpreter="${{ steps.py.outputs.python-path }}"
          PYTHONPATH=source/package $py_interpreter source/script/leco_model.py run documentation/configuration.toml documentation/run_commands_test
          PYTHONPATH=source/package $py_interpreter source/script/leco_model.py cluster --method feed_forward documentation/run_commands_test
          PYTHONPATH=source/package $py_interpreter source/script/leco_model.py plot documentation/configuration.toml documentation/run_commands_test/population.gpkg
      - name: Run tests
        run: |
          py_interpreter="${{ steps.py.outputs.python-path }}"
          PYTHONPATH=source/package $py_interpreter source/test/run_all_tests.py
      - name: Check requirements
        run: |
          py_interpreter="${{ steps.py.outputs.python-path }}"
          PYTHONPATH=source/package $py_interpreter source/script/leco_model.py --help
      - name: Create documentation
        run: |
          sphinx-build -M html documentation documentation_build
      - name: Create package
        run: |
          py_interpreter="${{ steps.py.outputs.python-path }}"
          PYTHONPATH=source/package $py_interpreter -m build --wheel --outdir dist .
